export { default as TheHero } from './TheHero'
export { default as TheSlider } from './TheSlider'
export { default as TheImage } from './TheImage'
export { default as TheText } from './TheText'
export { default as TheFaq } from './TheAccordion'
export { default as NewsForm } from './TheForm'
